- name: Install Nginx
  become: yes
  become_user: root
  apt:
    name:
    - nginx
    update_cache: yes

- name: Deploy nginx.conf
  copy:
    src: "nginx.conf"
    dest: "/etc/nginx/nginx.conf"
    owner: "root"
    group: "root"
    mode: "0644"


- name: Install Package(MYSQL)
  become: yes
  become_user: root
  apt:
    name:
    - mysql-server-5.7
    - mysql-server-core-5.7
    - mysql-common
    - mysql-client-5.7
    - mysql-client-core-5.7
    update_cache: yes

- name: Upgrade pip
  environment: &env
    PATH: "/home/isucon/bin:/home/isucon/.local/bin:/usr/local/node/bin:/usr/local/python/bin:/usr/local/go/bin:/home/isucon/go/bin:/usr/local/bin:/usr/bin:/bin"
  pip:
    name: pip
    executable: pip3
    state: latest

- name: Set Temporary password
  become: yes
  become_user: root
  blockinfile:
    create: yes
    dest: &myCnf /root/.my.cnf
    content: |
      [client]
      user = root
      password = root

- name: Create isucon user on MySQL
  become: yes
  become_user: root
  shell: |
      mysql -uroot -proot -e "GRANT ALL PRIVILEGES ON *.* TO isucon@localhost IDENTIFIED BY 'isucon' WITH GRANT OPTION; FLUSH PRIVILEGES;"

- name: Remove Temporary file
  become: yes
  become_user: root
  file:
    path: *myCnf
    state: absent

- name: Copy mysqld.conf
  become: yes
  become_user: root
  copy:
    src: "mysqld.cnf"
    dest: "/etc/mysql/mysql.conf.d/mysqld.cnf"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Install Faker for Initialize Data
  become: yes
  become_user: root
  environment: 
    << *env
  pip:
    executable: pip3
    name: Faker

- name: Make initial data
  become: yes
  become_user: root
  args:
    chdir: /home/isucon/isucon10-qualify/initial-data
  environment: 
    << *env
  command: make all

- name: Setup MySQL
  become: yes
  become_user: isucon
  args:
    chdir: /home/isucon/isucon10-qualify
  environment:
    << *env
  shell: |
    mysql -u isucon -pisucon < webapp/mysql/db/0_Schema.sql
